# Note: the first 2 entries are not used by the "es" version
base_endpoint: localhost:3002
api_key: private_xxxxxxxxx
index_name: my-index
index: True
archive: False
archivedir: /home/bob/gitter-messages
